name: abc
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  barcode_scan: ^0.0.3
  device_info: ^0.2.1
  connectivity: ^0.3.1
  http: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - batman.png
